# Prometheus configuration with persistence
server:
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: ""  # Uses default storage class
    accessModes:
      - ReadWriteOnce
  retention: "15d"  # Keep metrics for 15 days

alertmanager:
  persistentVolume:
    enabled: true
    size: 2Gi
    storageClass: ""
    accessModes:
      - ReadWriteOnce

# Disable components you might not need in minikube
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
pushgateway:
  enabled: false
